# 國家代碼和名稱映射
COUNTRIES = {
    "AE": "United Arab Emirates",
    "AM": "Armenia", 
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "BA": "Bosnia and Herzegovina",
    "BD": "Bangladesh",
    "BG": "Bulgaria",
    "BR": "Brazil",
    "BY": "Belarus",
    "CA": "Canada",
    "CH": "Switzerland",
    "CN": "China",
    "CO": "Colombia",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "EE": "Estonia",
    "EG": "Egypt",
    "ES": "Spain",
    "FR": "France",
    "GB": "United Kingdom",
    "GR": "Greece",
    "HK": "Hong Kong",
    "ID": "Indonesia",
    "IN": "India",
    "IQ": "Iraq",
    "IR": "Iran",
    "IT": "Italy",
    "JP": "Japan",
    "KH": "Cambodia",
    "KR": "South Korea",
    "KZ": "Kazakhstan",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LY": "Libya",
    "ME": "Montenegro",
    "MK": "North Macedonia",
    "MN": "Mongolia",
    "MX": "Mexico",
    "MY": "Malaysia",
    "NL": "Netherlands",
    "PE": "Peru",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "SA": "Saudi Arabia",
    "SE": "Sweden",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SN": "Senegal",
    "TH": "Thailand",
    "TN": "Tunisia",
    "TT": "Trinidad and Tobago",
    "TZ": "Tanzania",
    "US": "United States",
    "UZ": "Uzbekistan",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}